React Todo App
jeanbuhendwa/Todo-App-react pull request #1
Opened 2023-03-30 17:47 UTC by jeanbuhendwa

In this pull request I have created a todo app using react js

2023-03-30 22:00 UTC, ikoote1 requested changes
Hi @jeanbuhendwa ,

You are amazing 😃 👏 . You did a very great job in implementing almost all the required parts of the project.
![image](https://user-images.githubusercontent.com/96288581/228971781-f5f0b045-d94a-4016-b756-eaebf4f695f9.png)
That is you!

### Highlights 👏 🎩
- [ ] No linter errors 👍
- [ ] Good use of React styles 👍
- [ ] Good use of React router 👍

**it is just that there are some few changes you need, to make your project more perfect**
### Optional suggestions 🛩️
 Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-30 22:00 UTC, ikoote1 commented on README.md
> +    - [Key Features](#key-features)
You went the extra mile to fill in all the required parts of the readme file. But I would suggest that you give detailed information about the project. This will help visitors to understand more about your project before cloning or checking for its live demo.

2023-03-30 22:00 UTC, ikoote1 commented on src/components/NavBar.jsx
> +  );
I really appreciate the way you are navigating through all project, check [react](https://www.youtube.com/watch?v=1wZoGFF_oi4&list=PLZlA0Gpn_vH_NT5zPVp18nGe_W9LqBDQK) for other better ways of navigation.

2023-03-30 22:00 UTC, ikoote1 commented on src/components/TodoItem.jsx
> +  };
OPTIONAL: It brings a lot of pleasure to know that there is someone who can use inline and in-code styling like this. It is just that it always looks perfect and professional to make use of external styling. It simplifies the code and helps other people to understand your UI and design.

2023-04-01 20:11 UTC, jeanbuhendwa commented
Thanks @ikoote1. I will work on the changes that you suggested.

2023-04-01 20:12 UTC, merged